### ISSUE TITLE
错误参考子页面任务认领

### ISSUE THREAD

**Issue by liruifengv** [liruifengv/docs#4]
[错误参考](https://docs.astro.build/zh-cn/reference/error-reference/)的子页面都需要翻译和更新。
比如 https://docs.astro.build/zh-cn/reference/errors/middleware-not-aresponse/

请在此issue下评论，认领错误参考子页面翻译任务

### 注意，错误索引页面的 标题 title 不翻译！！！

这些都是 Astro 的报错信息，索引页面是让用户根据报错信息来查找，所以报错信息不做翻译。

英文原文都是根据 Astro 主仓库的代码自动生成的，感兴趣的可查看：

![704fa8700595f4730edb7ff337f5de6](https://github.com/liruifengv/docs/assets/25167721/563686e5-3007-473f-b699-db42b7529bb8)

此处统一，标题不翻译，描述翻译，例如：
![image](https://github.com/liruifengv/docs/assets/25167721/d7ec88a8-994c-495f-9927-df41a2eb39a9)

**Comment by Liqiaomiao** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
error-reference | [UnknownContentCollectionError](https://docs.astro.build/en/reference/errors/unknown-content-collection-error/) | @Liqiaomiao   | 2027.07.28 - 2027.07.29
error-reference |  [InvalidContentEntryFrontmatterError](https://docs.astro.build/en/reference/errors/invalid-content-entry-frontmatter-error/) | @Liqiaomiao   | 2027.07.28 - 2027.07.29
error-reference |  [InvalidContentEntrySlugError](https://docs.astro.build/en/reference/errors/invalid-content-entry-slug-error/) | @Liqiaomiao   | 2027.07.28 - 2027.07.29
error-reference |  [ContentSchemaContainsSlugError](https://docs.astro.build/en/reference/errors/content-schema-contains-slug-error/) | @Liqiaomiao   | 2027.07.28 - 2027.07.29

**Comment by CaptainOfPhB** [comment]
| Setion | Title | Translator | Estimated Finish Time |
| ------ | ----- | ----- | --------------- |
| [Error Reference](https://docs.astro.build/en/reference/error-reference/) |[PrerenderDynamicEndpointPathCollide](https://docs.astro.build/en/reference/errors/prerender-dynamic-endpoint-path-collide/) | @CaptainOfPhB | 2027.07.28 |
| [Error Reference](https://docs.astro.build/en/reference/error-reference/) |[ExpectedImage](https://docs.astro.build/en/reference/errors/expected-image/) | @CaptainOfPhB | 2027.07.28 |
| [Error Reference](https://docs.astro.build/en/reference/error-reference/) |[ExpectedImageOptions](https://docs.astro.build/en/reference/errors/expected-image-options/)| @CaptainOfPhB | 2027.07.28 |
| [Error Reference](https://docs.astro.build/en/reference/error-reference/) | [MarkdownImageNotFound](https://docs.astro.build/en/reference/errors/markdown-image-not-found/) | @CaptainOfPhB | 2027.07.28 |
| [Error Reference](https://docs.astro.build/en/reference/error-reference/) | [ResponseSentError](https://docs.astro.build/en/reference/errors/response-sent-error/) | @CaptainOfPhB | 2027.07.28 |
| [Error Reference](https://docs.astro.build/en/reference/error-reference/) | [MiddlewareNoDataOrNextCalled](https://docs.astro.build/en/reference/errors/middleware-no-data-or-next-called/) | @CaptainOfPhB | 2027.07.28 |
| [Error Reference](https://docs.astro.build/en/reference/error-reference/) | [MiddlewareNotAResponse](https://docs.astro.build/en/reference/errors/middleware-not-aresponse/) | @CaptainOfPhB | 2027.07.28 |
| [Error Reference](https://docs.astro.build/en/reference/error-reference/) | [LocalsNotAnObject](https://docs.astro.build/en/reference/errors/locals-not-an-object/) | @CaptainOfPhB | 2027.07.28 |
| [Error Reference](https://docs.astro.build/en/reference/error-reference/) | [LocalImageUsedWrongly](https://docs.astro.build/en/reference/errors/local-image-used-wrongly/) | @CaptainOfPhB | 2027.07.28 |
| [Error Reference](https://docs.astro.build/en/reference/error-reference/) | [AstroGlobUsedOutside](https://docs.astro.build/en/reference/errors/astro-glob-used-outside/) | @CaptainOfPhB | 2027.07.28 |
| [Error Reference](https://docs.astro.build/en/reference/error-reference/) | [AstroGlobNoMatch](https://docs.astro.build/en/reference/errors/astro-glob-no-match/) | @CaptainOfPhB | 2027.07.28 |
| [Error Reference](https://docs.astro.build/en/reference/error-reference/) | [RedirectWithNoLocation](https://docs.astro.build/en/reference/errors/redirect-with-no-location/) | @CaptainOfPhB | 2027.07.28 |
| [Error Reference](https://docs.astro.build/en/reference/error-reference/) | [InvalidDynamicRoute](https://docs.astro.build/en/reference/errors/invalid-dynamic-route/) | @CaptainOfPhB | 2027.07.28 |
| [Error Reference](https://docs.astro.build/en/reference/error-reference/) | [UnknownViteError](https://docs.astro.build/en/reference/errors/unknown-vite-error/) | @CaptainOfPhB | 2027.07.28 |
| [Error Reference](https://docs.astro.build/en/reference/error-reference/) | [FailedToLoadModuleSSR](https://docs.astro.build/en/reference/errors/failed-to-load-module-ssr/) | @CaptainOfPhB | 2027.07.28 |
| [Error Reference](https://docs.astro.build/en/reference/error-reference/) | [InvalidGlob](https://docs.astro.build/en/reference/errors/invalid-glob/) | @CaptainOfPhB | 2027.07.28 |
| [Error Reference](https://docs.astro.build/en/reference/error-reference/) | [UnknownMarkdownError (EN)](https://docs.astro.build/en/reference/errors/unknown-markdown-error/) | @CaptainOfPhB | 2027.07.28 |
| [Error Reference](https://docs.astro.build/en/reference/error-reference/) | [MarkdownFrontmatterParseError (EN)](https://docs.astro.build/en/reference/errors/markdown-frontmatter-parse-error/) | @CaptainOfPhB | 2027.07.28 |
| [Error Reference](https://docs.astro.build/en/reference/error-reference/) | [InvalidFrontmatterInjectionError (EN)](https://docs.astro.build/en/reference/errors/invalid-frontmatter-injection-error/) | @CaptainOfPhB | 2027.07.28 |
| [Error Reference](https://docs.astro.build/en/reference/error-reference/) | [MdxIntegrationMissingError (EN)](https://docs.astro.build/en/reference/errors/mdx-integration-missing-error/) | @CaptainOfPhB | 2027.07.28 |
| [Error Reference](https://docs.astro.build/en/reference/error-reference/) | [UnknownConfigError (EN)](https://docs.astro.build/en/reference/errors/unknown-config-error/) | @CaptainOfPhB | 2027.07.28 |
| [Error Reference](https://docs.astro.build/en/reference/error-reference/) | [ConfigNotFound (EN)](https://docs.astro.build/en/reference/errors/config-not-found/) | @CaptainOfPhB | 2027.07.28 |
| [Error Reference](https://docs.astro.build/en/reference/error-reference/) | [ConfigLegacyKey](https://docs.astro.build/en/reference/errors/config-legacy-key/) | @CaptainOfPhB | 2027.07.28 |

**Comment by eiis** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
error-reference |  Unknown CSS Error | @fuguid   | 2027.07.28 - 2027.07.28
error-reference |  CSS Syntax Error | @fuguid   | 2027.07.28 - 2027.07.28
